# https://taskfile.dev

version: '3'

vars:
  BACKEND_DIR: backend
  FRONTEND_DIR: frontend

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list
    silent: true

  setup:
    desc: Setup both backend and frontend dependencies
    deps: [setup-backend, setup-frontend]

  setup-backend:
    desc: Install backend dependencies
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - /Users/roei/dev_workspace/virtual_envs/agentic-company/bin/pip install -r requirements.txt
    sources:
      - requirements.txt
    generates:
      - .venv/pyvenv.cfg

  setup-frontend:
    desc: Install frontend dependencies
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - npm install
    sources:
      - package.json
    generates:
      - node_modules/.package-lock.json

  backend:
    desc: Run the backend server
    dir: "{{.BACKEND_DIR}}"
    deps: [setup-backend]
    cmds:
      - /Users/roei/dev_workspace/virtual_envs/agentic-company/bin/python -m app.main

  frontend:
    desc: Run the frontend development server
    dir: "{{.FRONTEND_DIR}}"
    deps: [setup-frontend]
    cmds:
      - npm run dev

  dev:
    desc: Run both backend and frontend in parallel
    deps: [setup]
    cmds:
      - task backend &
      - task frontend

  clean:
    desc: Clean dependencies and build artifacts
    cmds:
      - rm -rf {{.BACKEND_DIR}}/.venv
      - rm -rf {{.BACKEND_DIR}}/__pycache__
      - rm -rf {{.BACKEND_DIR}}/app/__pycache__
      - rm -rf {{.FRONTEND_DIR}}/node_modules
      - rm -rf {{.FRONTEND_DIR}}/.next

  check-env:
    desc: Check if required environment variables are set
    cmds:
      - |
        if [ -z "$OPENAI_API_KEY" ]; then
          echo "❌ OPENAI_API_KEY not set. Please set it in your environment or .env file"
          exit 1
        else
          echo "✅ OPENAI_API_KEY is set"
        fi
